/* eslint-disable */
// AUTO-GENERATED by scripts/export-abi.mjs — do not edit by hand.
export const RATING_CONTROLLER_ADDRESSES = {
  84532: "0x88b467bf29a88b5a7b6d351f74b26a18baf8f373",
} as const;

export const RATING_CONTROLLER_BASE_SEPOLIA = RATING_CONTROLLER_ADDRESSES[84532];

export function getRatingControllerAddress(chainId: number): `0x${string}` {
  const address =
    RATING_CONTROLLER_ADDRESSES[chainId as keyof typeof RATING_CONTROLLER_ADDRESSES];
  if (!address) {
    throw new Error(`No deployment address found for chainId ${chainId}`);
  }
  return address as `0x${string}`;
}
