/* eslint-disable */
// AUTO-GENERATED by scripts/export-abi.mjs — do not edit by hand.
export const RATING_CONTROLLER_ADDRESSES = {
  84532: "0xe83d248193e5cdb0db89ecd113feb1c4d0fe9e96",
} as const;

export const RATING_CONTROLLER_BASE_SEPOLIA = RATING_CONTROLLER_ADDRESSES[84532];

export function getRatingControllerAddress(chainId: number): `0x${string}` {
  const address =
    RATING_CONTROLLER_ADDRESSES[chainId as keyof typeof RATING_CONTROLLER_ADDRESSES];
  if (!address) {
    throw new Error(`No deployment address found for chainId ${chainId}`);
  }
  return address as `0x${string}`;
}
