/* eslint-disable */
// AUTO-GENERATED by scripts/export-abi.mjs — do not edit by hand.
export const ratingControllerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_oracleAgent",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelPendingRequest",
    "inputs": [
      {
        "name": "targetUal",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "fulfillPhase1",
    "inputs": [
      {
        "name": "targetUal",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "score",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "rKaUal",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getRating",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct RatingController.RatingRecord",
        "components": [
          {
            "name": "phase",
            "type": "uint8",
            "internalType": "enum RatingController.Phase"
          },
          {
            "name": "isPending",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "phase1Score",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "phase2Score",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "phase3Score",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "rKaUal",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRatingByUal",
    "inputs": [
      {
        "name": "targetUal",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct RatingController.RatingRecord",
        "components": [
          {
            "name": "phase",
            "type": "uint8",
            "internalType": "enum RatingController.Phase"
          },
          {
            "name": "isPending",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "phase1Score",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "phase2Score",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "phase3Score",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "rKaUal",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRequestId",
    "inputs": [
      {
        "name": "targetUal",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "oracleAgent",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "requestPhase1",
    "inputs": [
      {
        "name": "targetUal",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOracleAgent",
    "inputs": [
      {
        "name": "_newOracleAgent",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "OracleAgentUpdated",
    "inputs": [
      {
        "name": "newAgent",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Phase1Fulfilled",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "targetUal",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "score",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "rKaUal",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Phase1Requested",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "targetUal",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "requester",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RequestCancelled",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "targetUal",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyRKaUal",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyUal",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidOracleAgent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidPhase",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidScore",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnauthorizedCaller",
    "inputs": []
  }
] as const;
