#!/usr/bin/env node
/**
 * Extract RatingController ABI + Base Sepolia deployment address from Forge
 * artifacts and write TypeScript sources under packages/contracts/ts/.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const FALLBACK_BASE_SEPOLIA = "0x9D53bdabB8Eb1c724323c5542d5C344B2d84B2Cc";
const BASE_SEPOLIA_CHAIN_ID = 84532;

const artifactPath = join(
  root,
  "out",
  "RatingController.sol",
  "RatingController.json"
);
const broadcastPath = join(
  root,
  "broadcast",
  "RatingController.s.sol",
  String(BASE_SEPOLIA_CHAIN_ID),
  "run-latest.json"
);
const tsDir = join(root, "ts");

function checksumAddress(address) {
  if (address.toLowerCase() === FALLBACK_BASE_SEPOLIA.toLowerCase()) {
    return FALLBACK_BASE_SEPOLIA;
  }
  if (/^0x[a-fA-F0-9]{40}$/.test(address)) {
    return address;
  }
  throw new Error(`Invalid address from broadcast: ${address}`);
}

function readAbi() {
  if (!existsSync(artifactPath)) {
    throw new Error(
      `Missing Forge artifact at ${artifactPath}. Run forge build first.`
    );
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error("Forge artifact missing abi array");
  }
  return artifact.abi;
}

function readDeployedAddress() {
  if (!existsSync(broadcastPath)) {
    console.warn(
      `[export-abi] No broadcast at ${broadcastPath}; using fallback ${FALLBACK_BASE_SEPOLIA}`
    );
    return FALLBACK_BASE_SEPOLIA;
  }

  const broadcast = JSON.parse(readFileSync(broadcastPath, "utf8"));
  const txs = Array.isArray(broadcast.transactions)
    ? broadcast.transactions
    : [];
  const create = txs.find(
    (tx) =>
      tx.contractName === "RatingController" && tx.transactionType === "CREATE"
  );

  if (!create?.contractAddress) {
    console.warn(
      `[export-abi] No RatingController CREATE in broadcast; using fallback ${FALLBACK_BASE_SEPOLIA}`
    );
    return FALLBACK_BASE_SEPOLIA;
  }

  return checksumAddress(create.contractAddress);
}

function writeAbiTs(abi) {
  const body = `/* eslint-disable */
// AUTO-GENERATED by scripts/export-abi.mjs — do not edit by hand.
export const ratingControllerAbi = ${JSON.stringify(abi, null, 2)} as const;
`;
  writeFileSync(join(tsDir, "ratingControllerAbi.ts"), body, "utf8");
}

function writeDeploymentsTs(address) {
  const lines = [
    "/* eslint-disable */",
    "// AUTO-GENERATED by scripts/export-abi.mjs — do not edit by hand.",
    "export const RATING_CONTROLLER_ADDRESSES = {",
    `  84532: "${address}",`,
    "} as const;",
    "",
    "export const RATING_CONTROLLER_BASE_SEPOLIA = RATING_CONTROLLER_ADDRESSES[84532];",
    "",
    "export function getRatingControllerAddress(chainId: number): `0x${string}` {",
    "  const address =",
    "    RATING_CONTROLLER_ADDRESSES[chainId as keyof typeof RATING_CONTROLLER_ADDRESSES];",
    "  if (!address) {",
    "    throw new Error(`No deployment address found for chainId ${chainId}`);",
    "  }",
    "  return address as `0x${string}`;",
    "}",
    "",
  ];
  writeFileSync(join(tsDir, "deployments.ts"), lines.join("\n"), "utf8");
}

mkdirSync(tsDir, { recursive: true });
const abi = readAbi();
const address = readDeployedAddress();
writeAbiTs(abi);
writeDeploymentsTs(address);
console.log(
  `[export-abi] Wrote ratingControllerAbi.ts and deployments.ts (${address})`
);
