export {
  DEO_DATASET_DESCRIPTION,
  DEO_MATERIALS,
  DEO_METHODS,
  DEO_RESULTS,
  RDF_TYPE,
  SCHEMA_ABOUT,
  SCHEMA_ADDITIONAL_TYPE,
  SCHEMA_AUTHOR,
  SCHEMA_CONTENT_URL,
  SCHEMA_CREATOR,
  SCHEMA_DATE_CREATED,
  SCHEMA_DESCRIPTION,
  SCHEMA_DISTRIBUTION,
  SCHEMA_ENCODING,
  SCHEMA_ENCODING_FORMAT,
  SCHEMA_HAS_PART,
  SCHEMA_IDENTIFIER,
  SCHEMA_MEDIA_OBJECT,
  SCHEMA_MENTIONS,
  SCHEMA_NAME,
  SCHEMA_PERSON,
  SCHEMA_POSITION,
  SCHEMA_RATING_VALUE,
  SCHEMA_SAME_AS,
  SCHEMA_SCHOLARLY_ARTICLE,
  SCHEMA_TEXT,
} from "./vocab.js";

export {
  publicationWithRatingBindingSchema,
} from "./types.js";

export type {
  PublicationAuthor,
  PublicationMetadata,
  PublicationResource,
  PublicationResourceKind,
  PublicationSection,
  PublicationSectionKind,
  PublicationWithRatingBinding,
  PublishAssertionDeps,
  PublishPublicationParams,
  PublishPublicationResult,
  RatingBinding,
  TargetAssetBinding,
} from "./types.js";
